# Generated by Django 3.2.6 on 2021-12-10 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("topics", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="topic",
            name="url_name",
            field=models.SlugField(max_length=64, unique=True),
        ),
    ]
