# Generated by Django 3.2.6 on 2021-12-13 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("topics", "0002_alter_topic_url_name"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="topic",
            options={"ordering": ["-updated_at"]},
        ),
    ]
